version: "3.7"

services: 
  app:
    image: app:latest
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - mysql
    volumes: 
      - ./view:/app/view
      - ./images:/app/images
    networks: 
      - bridge

  mysql:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "mismatch"
    networks: 
      - bridge
    volumes: 
      - ./sql:/docker-entrypoint-initdb.d:ro
      - mysql:/var/lib/mysql

  adminer:
    image: adminer:4
    networks: 
      - bridge
    ports:
      - 8080:8080
    depends_on: 
      - mysql

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./conf/web.conf:/etc/nginx/conf.d/default.conf:ro
    networks: 
      - bridge
    command: nginx -g 'daemon off;'

networks: 
  bridge:
    driver: bridge

volumes: 
  mysql: